# Generated by Django 4.0.4 on 2022-05-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doj', models.DateField()),
                ('comment', models.CharField(max_length=200)),
                ('a_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.artist')),
                ('b_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.band')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='a_name',
            field=models.ManyToManyField(through='blogs.Membership', to='blogs.artist'),
        ),
    ]
