# Generated by Django 4.0.4 on 2022-05-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_artist_band_membership_band_a_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_field', models.CharField(max_length=200)),
            ],
        ),
    ]
