# Generated by Django 4.0.4 on 2022-05-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_p_name_pizza_pizza_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppings',
            old_name='toppings_name',
            new_name='topping_name',
        ),
    ]
