# Generated by Django 4.0.4 on 2022-05-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_toppings_name_toppings_topping_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='toppings_name',
            new_name='topping_name',
        ),
    ]
