# Generated by Django 4.0.4 on 2022-05-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=200)),
                ('s_artist', models.CharField(max_length=200)),
                ('r_date', models.DateField()),
                ('s_genre', models.CharField(max_length=200)),
            ],
        ),
    ]
