# Generated by Django 4.0.4 on 2022-06-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(max_length=200)),
                ('m_name', models.CharField(max_length=200)),
                ('m_director', models.CharField(max_length=200)),
                ('m_rd', models.DateField()),
                ('m_genre', models.CharField(max_length=200)),
            ],
        ),
    ]
