# Generated by Django 4.0.4 on 2022-06-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_fooditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.CharField(max_length=200)),
                ('b_name', models.CharField(max_length=200)),
                ('b_author', models.CharField(max_length=200)),
                ('b_genre', models.CharField(max_length=200)),
            ],
        ),
    ]
